[package]
name = "nft_factory"
version = "1.0.0"
authors = []

[addresses]
movement = "0x1587c6b4727cbf382c8b21052d4d5292c78d324d508b9f7cbceda8dea9142fd7"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]
