[package]
name = "move_developer_portal"
version = "0.0.1"
upgrade_policy = "compatible"
authors = ["MovementLabs", "Jayden <jayden.vu@movementlabs.xyz>"]
license = "MIT"

[addresses]
movement = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]
